python main.py --lr 0.01 --output_dir lr_result_1
python main.py --lr 0.03 --output_dir lr_result_2
python main.py --lr 0.05 --output_dir lr_result_3
python main.py --lr 0.07 --output_dir lr_result_4
python main.py --lr 0.09 --output_dir lr_result_5
python main.py --lr 0.1 --output_dir lr_result_6
python main.py --lr 0.2 --output_dir lr_result_7
python main.py --lr 0.3 --output_dir lr_result_8
python main.py --lr 0.4 --output_dir lr_result_9
python main.py --lr 0.5 --output_dir lr_result_10
python main.py --lr 0.6 --output_dir lr_result_11
python main.py --lr 0.7 --output_dir lr_result_12
python main.py --lr 0.8 --output_dir lr_result_13
python main.py --lr 0.9 --output_dir lr_result_14
python main.py --lr 1.0 --output_dir lr_result_15
python main.py --lr 1.5 --output_dir lr_result_16
python main.py --lr 2.0 --output_dir lr_result_17
python main.py --lr 3.0 --output_dir lr_result_18
python main.py --lr 4.0 --output_dir lr_result_19
python main.py --lr 5.0 --output_dir lr_result_20
python main.py --lr 10.0 --output_dir lr_result_21