python main.py --lr 5 --momentum 0.01 --output_dir momentum_result_1
python main.py --lr 5 --momentum 0.05 --output_dir momentum_result_2
python main.py --lr 5  --momentum 0.1 --output_dir momentum_result_3
python main.py --lr 5  --momentum 0.15 --output_dir momentum_result_4
python main.py --lr 5  --momentum 0.2 --output_dir momentum_result_5
python main.py --lr 5  --momentum 0.25 --output_dir momentum_result_6
python main.py --lr 5  --momentum 0.3 --output_dir momentum_result_7
python main.py --lr 5  --momentum 0.35 --output_dir momentum_result_8
python main.py --lr 5  --momentum 0.4 --output_dir momentum_result_9
python main.py --lr 5  --momentum 0.45 --output_dir momentum_result_10
python main.py --lr 5  --momentum 0.5 --output_dir momentum_result_11
python main.py --lr 5  --momentum 0.6 --output_dir momentum_result_12
python main.py --lr 5  --momentum 0.65 --output_dir momentum_result_13
python main.py --lr 5  --momentum 0.7 --output_dir momentum_result_14
python main.py --lr 5  --momentum 0.75 --output_dir momentum_result_15
python main.py --lr 5  --momentum 0.8 --output_dir momentum_result_16
python main.py --lr 5  --momentum 0.85 --output_dir momentum_result_17
python main.py --lr 5  --momentum 0.9 --output_dir momentum_result_18
python main.py --lr 5  --momentum 0.95 --output_dir momentum_result_19
python main.py --lr 5  --momentum 0.99 --output_dir momentum_result_20