python main.py --lr 0.1 --momentum 0.01 --output_dir momentum_result_lr_small_1
python main.py --lr 0.1 --momentum 0.05 --output_dir momentum_result_lr_small_2
python main.py --lr 0.1  --momentum 0.1 --output_dir momentum_result_lr_small_3
python main.py --lr 0.1  --momentum 0.15 --output_dir momentum_result_lr_small_4
python main.py --lr 0.1  --momentum 0.2 --output_dir momentum_result_lr_small_5
python main.py --lr 0.1  --momentum 0.25 --output_dir momentum_result_lr_small_6
python main.py --lr 0.1  --momentum 0.3 --output_dir momentum_result_lr_small_7
python main.py --lr 0.1  --momentum 0.35 --output_dir momentum_result_lr_small_8
python main.py --lr 0.1  --momentum 0.4 --output_dir momentum_result_lr_small_9
python main.py --lr 0.1  --momentum 0.45 --output_dir momentum_result_lr_small_10
python main.py --lr 0.1  --momentum 0.5 --output_dir momentum_result_lr_small_11
python main.py --lr 0.1  --momentum 0.6 --output_dir momentum_result_lr_small_12
python main.py --lr 0.1  --momentum 0.65 --output_dir momentum_result_lr_small_13
python main.py --lr 0.1  --momentum 0.7 --output_dir momentum_result_lr_small_14
python main.py --lr 0.1  --momentum 0.75 --output_dir momentum_result_lr_small_15
python main.py --lr 0.1  --momentum 0.8 --output_dir momentum_result_lr_small_16
python main.py --lr 0.1  --momentum 0.85 --output_dir momentum_result_lr_small_17
python main.py --lr 0.1  --momentum 0.9 --output_dir momentum_result_lr_small_18
python main.py --lr 0.1  --momentum 0.95 --output_dir momentum_result_lr_small_19
python main.py --lr 0.1  --momentum 0.99 --output_dir momentum_result_lr_small_20