python main.py --lr 2 --momentum 0.01 --output_dir momentum_result_medium_lr_1
python main.py --lr 2 --momentum 0.05 --output_dir momentum_result_medium_lr_2
python main.py --lr 2  --momentum 0.1 --output_dir momentum_result_medium_lr_3
python main.py --lr 2  --momentum 0.15 --output_dir momentum_result_medium_lr_4
python main.py --lr 2  --momentum 0.2 --output_dir momentum_result_medium_lr_5
python main.py --lr 2  --momentum 0.25 --output_dir momentum_result_medium_lr_6
python main.py --lr 2  --momentum 0.3 --output_dir momentum_result_medium_lr_7
python main.py --lr 2  --momentum 0.35 --output_dir momentum_result_medium_lr_8
python main.py --lr 2  --momentum 0.4 --output_dir momentum_result_medium_lr_9
python main.py --lr 2  --momentum 0.45 --output_dir momentum_result_medium_lr_10
python main.py --lr 2  --momentum 0.5 --output_dir momentum_result_medium_lr_11
python main.py --lr 2  --momentum 0.6 --output_dir momentum_result_medium_lr_12
python main.py --lr 2  --momentum 0.65 --output_dir momentum_result_medium_lr_13
python main.py --lr 2  --momentum 0.7 --output_dir momentum_result_medium_lr_14
python main.py --lr 2  --momentum 0.75 --output_dir momentum_result_medium_lr_15
python main.py --lr 2  --momentum 0.8 --output_dir momentum_result_medium_lr_16
python main.py --lr 2  --momentum 0.85 --output_dir momentum_result_medium_lr_17
python main.py --lr 2  --momentum 0.9 --output_dir momentum_result_medium_lr_18
python main.py --lr 2  --momentum 0.95 --output_dir momentum_result_medium_lr_19
python main.py --lr 2  --momentum 0.99 --output_dir momentum_result_medium_lr_20