python main_QHM.py --lr 0.01 --output_dir optimum_result_1
python main_QHM.py --lr 0.012 --output_dir optimum_result_2
python main_QHM.py --lr 0.012 --output_dir optimum_result_2
python main_QHM.py --lr 0.012 --output_dir optimum_result_2
python main_QHM.py --lr 0.012 --output_dir optimum_result_2
python main_QHM.py --lr 0.014 --output_dir optimum_result_3
python main_QHM.py --lr 0.016 --output_dir optimum_result_4
python main_QHM.py --lr 0.018 --output_dir optimum_result_5
python main_QHM.py --lr 0.02 --output_dir optimum_result_6
python main_QHM.py --lr 0.022 --output_dir optimum_result_7
python main_QHM.py --lr 0.024 --output_dir optimum_result_8
python main_QHM.py --lr 0.026 --output_dir optimum_result_9
python main_QHM.py --lr 0.028 --output_dir optimum_result_10
python main_QHM.py --lr 0.03 --output_dir optimum_result_11
python main_QHM.py --lr 0.032 --output_dir optimum_result_12
python main_QHM.py --lr 0.034 --output_dir optimum_result_13
python main_QHM.py --lr 0.036 --output_dir optimum_result_14
python main_QHM.py --lr 0.038 --output_dir optimum_result_15
python main_QHM.py --lr 0.04 --output_dir optimum_result_16
python main_QHM.py --lr 0.042 --output_dir optimum_result_17
python main_QHM.py --lr 0.044 --output_dir optimum_result_18
python main_QHM.py --lr 0.046 --output_dir optimum_result_19
python main_QHM.py --lr 0.048 --output_dir optimum_result_20
python main_QHM.py --lr 0.05 --output_dir optimum_result_21